services:
  web:
    build: .
    container_name: happyaspa_web
    restart: always
    ports:
      # 将标准的 HTTPS 443 端口映射给容器
      - "443:5000"
    environment:
      - DATABASE_URL=sqlite:////app/instance/happyaspa.db
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
      # 把服务器全局目录下的证书，挂载到容器里的 /app/ssl 文件夹下
      - /root/ssl/dii:/app/ssl