"""add board column to forum_posts

Revision ID: 01f67ceafa1c
Revises: 9b9582f4916d
Create Date: 2026-03-25 19:39:01.100813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f67ceafa1c'
down_revision = '9b9582f4916d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_column('board')

    # ### end Alembic commands ###
