"""add parent_id to forum_comments

Revision ID: 05b649573024
Revises: 79f0e4dd884d
Create Date: 2026-03-18 16:01:19.132484

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "05b649573024"
down_revision = "79f0e4dd884d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forum_comments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_forum_comments_parent_id", "forum_comments", ["parent_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forum_comments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("parent_id")

    # ### end Alembic commands ###
