"""add attribution fields to listening_exercise

Revision ID: 065dab6ae8d0
Revises: d9267fcc1a1b
Create Date: 2026-04-01 17:57:39.650838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065dab6ae8d0'
down_revision = 'd9267fcc1a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_platform', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_modified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.drop_column('is_modified')
        batch_op.drop_column('source_platform')

    # ### end Alembic commands ###
