"""add notes and key_vocab to listening_exercises

Revision ID: 074f10ff2d88
Revises: 80912fcd13bd
Create Date: 2026-04-02 16:05:37.301644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074f10ff2d88'
down_revision = '80912fcd13bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
