"""add orchard models

Revision ID: 2cf5dd70cf9d
Revises: abd815a13c5e
Create Date: 2026-03-30 17:57:44.890615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf5dd70cf9d'
down_revision = 'abd815a13c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchard_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('effect_value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orchard_land_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('upgrade_cost', sa.Integer(), nullable=True),
    sa.Column('rare_boost', sa.Float(), nullable=True),
    sa.Column('growth_reduction', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orchard_seed_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('growth_hours', sa.Integer(), nullable=True),
    sa.Column('is_mystery', sa.Boolean(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orchard_fruit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('drop_rate', sa.Float(), nullable=True),
    sa.Column('is_showcase_worthy', sa.Boolean(), nullable=True),
    sa.Column('academic_element', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seed_type_id'], ['orchard_seed_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_orchard_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='unique_user_item')
    )
    op.create_table('user_orchards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_harvests', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('weekly_points', sa.Integer(), nullable=True),
    sa.Column('last_weekly_reset', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_lands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orchard_id', sa.Integer(), nullable=False),
    sa.Column('land_type_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('current_seed_id', sa.Integer(), nullable=True),
    sa.Column('plant_status', sa.String(length=20), nullable=True),
    sa.Column('planted_at', sa.DateTime(), nullable=True),
    sa.Column('matures_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_seed_id'], ['orchard_seed_types.id'], ),
    sa.ForeignKeyConstraint(['land_type_id'], ['orchard_land_types.id'], ),
    sa.ForeignKeyConstraint(['orchard_id'], ['user_orchards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_harvested_fruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fruit_type_id', sa.Integer(), nullable=False),
    sa.Column('land_id', sa.Integer(), nullable=True),
    sa.Column('harvested_at', sa.DateTime(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fruit_type_id'], ['orchard_fruit_types.id'], ),
    sa.ForeignKeyConstraint(['land_id'], ['user_lands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_showcase_fruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orchard_id', sa.Integer(), nullable=False),
    sa.Column('harvested_fruit_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('display_message', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['harvested_fruit_id'], ['user_harvested_fruits.id'], ),
    sa.ForeignKeyConstraint(['orchard_id'], ['user_orchards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('total_correct_questions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_listening_duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('total_listening_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_correct_questions',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))

    op.drop_table('user_showcase_fruits')
    op.drop_table('user_harvested_fruits')
    op.drop_table('user_lands')
    op.drop_table('user_orchards')
    op.drop_table('user_orchard_inventory')
    op.drop_table('orchard_fruit_types')
    op.drop_table('orchard_seed_types')
    op.drop_table('orchard_land_types')
    op.drop_table('orchard_items')
    # ### end Alembic commands ###
