"""update_vacabularyword

Revision ID: 2e25483ec5a7
Revises: 9c2a1c1b2d4e
Create Date: 2026-03-19 17:25:38.804322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e25483ec5a7'
down_revision = '9c2a1c1b2d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_schedule_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_schedule_items_user_id_scheduled_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_schedule_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_schedule_items_user_id_scheduled_date'), ['user_id', 'scheduled_date'], unique=False)

    # ### end Alembic commands ###
