"""add questions list to listening

Revision ID: 44d725adc086
Revises: f6b07f736cb6
Create Date: 2026-03-13 09:45:27.058201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d725adc086'
down_revision = 'f6b07f736cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.drop_column('questions')

    # ### end Alembic commands ###
