"""add_accent_field_to_listening_exercise

Revision ID: 5e91972af4f7
Revises: 01f67ceafa1c
Create Date: 2026-03-26 16:45:42.732881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e91972af4f7'
down_revision = '01f67ceafa1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accent', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.drop_column('accent')

    # ### end Alembic commands ###
