"""add academic scenario models

Revision ID: 67f8affd089d
Revises: 49cfded8f5eb
Create Date: 2026-03-21 15:11:33.364325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f8affd089d'
down_revision = '49cfded8f5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('reference_material', sa.Text(), nullable=True),
    sa.Column('prep_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_scenario_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('audio_filename', sa.String(length=256), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score_vocabulary', sa.Float(), nullable=True),
    sa.Column('score_logic', sa.Float(), nullable=True),
    sa.Column('score_politeness', sa.Float(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['academic_scenarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_scenario_submissions')
    op.drop_table('academic_scenarios')
    # ### end Alembic commands ###
