"""Add notes function to UserListeningProgress

Revision ID: 6830c5823ebd
Revises: 06f1b19cf838
Create Date: 2026-03-27 15:22:45.197358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6830c5823ebd'
down_revision = '06f1b19cf838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
