"""Add notes_history to user_listening_progress

Revision ID: 76599cff4d57
Revises: 994a50e80fa1
Create Date: 2026-03-30 17:20:42.376594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76599cff4d57'
down_revision = '994a50e80fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.drop_column('notes_history')

    # ### end Alembic commands ###
