"""add creator_id to speaking_exercises

Revision ID: 79f0e4dd884d
Revises: 9c2a1c1b2d4e
Create Date: 2026-03-17 15:37:38.157161

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "79f0e4dd884d"
down_revision = "9c2a1c1b2d4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("speaking_exercises", schema=None) as batch_op:
        batch_op.add_column(sa.Column("creator_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_speaking_creator_id", "users", ["creator_id"], ["id"]
        )
    with op.batch_alter_table("user_schedule_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_schedule_items_user_id_scheduled_date"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_schedule_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_schedule_items_user_id_scheduled_date"),
            ["user_id", "scheduled_date"],
            unique=False,
        )

    with op.batch_alter_table("speaking_exercises", schema=None) as batch_op:
        batch_op.drop_constraint("fk_speaking_creator_id", type_="foreignkey")
        batch_op.drop_column("creator_id")

    # ### end Alembic commands ###
