"""add_shadowing_tables

Revision ID: 7a5b37ab6ebc
Revises: 3bc29812953b
Create Date: 2026-03-25 17:41:01.627900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5b37ab6ebc'
down_revision = '3bc29812953b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadowing_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('focus', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('duration_str', sa.String(length=20), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shadowing_audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('accent_code', sa.String(length=10), nullable=False),
    sa.Column('audio_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['shadowing_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shadowing_audios')
    op.drop_table('shadowing_exercises')
    # ### end Alembic commands ###
