"""revert to json fields for compatibility

Revision ID: 7a8c2ad446e5
Revises: e66c2900c919
Create Date: 2026-03-27 10:25:55.893710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8c2ad446e5'
down_revision = 'e66c2900c919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.alter_column('permanent_answered',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('permanent_correct',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.alter_column('permanent_correct',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('permanent_answered',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
