"""adjust fields to record user listening practise progress

Revision ID: 7ca8407d06b2
Revises: 01f67ceafa1c
Create Date: 2026-03-26 18:20:20.596194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca8407d06b2'
down_revision = '01f67ceafa1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permanent_answered', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('permanent_correct', sa.JSON(), nullable=True))
        batch_op.drop_column('score')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_correct_questions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_listening_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_listening_duration')
        batch_op.drop_column('total_correct_questions')

    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=True))
        batch_op.drop_column('permanent_correct')
        batch_op.drop_column('permanent_answered')

    # ### end Alembic commands ###
