"""add_puzzle_limit_columns

Revision ID: 8530d4d43976
Revises: 18b75ff8509d
Create Date: 2026-04-02 17:18:08.287000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8530d4d43976'
down_revision = '18b75ff8509d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_puzzle_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('daily_puzzle_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_puzzle_count')
        batch_op.drop_column('last_puzzle_date')

    # ### end Alembic commands ###
