"""add notes and key words to listening practise again

Revision ID: 994a50e80fa1
Revises: a73c16aa4625
Create Date: 2026-03-30 15:36:29.248242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994a50e80fa1'
down_revision = 'a73c16aa4625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_vocab', sa.JSON(), nullable=True))

    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.drop_column('key_vocab')

    # ### end Alembic commands ###
