"""Add forum economy and english proficiency fields

Revision ID: 9b9582f4916d
Revises: 3bc29812953b
Create Date: 2026-03-25 19:01:53.818084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9582f4916d'
down_revision = '3bc29812953b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_checkin_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_post_reward_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gaokao_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ielts_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('toefl_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gre_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_guide_qualified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_guide_qualified')
        batch_op.drop_column('gre_score')
        batch_op.drop_column('toefl_score')
        batch_op.drop_column('ielts_score')
        batch_op.drop_column('gaokao_score')
        batch_op.drop_column('last_post_reward_date')
        batch_op.drop_column('last_checkin_date')
        batch_op.drop_column('coins')

    # ### end Alembic commands ###
