"""add notes and key words to listening practise

Revision ID: a73c16aa4625
Revises: abd815a13c5e
Create Date: 2026-03-30 15:32:41.837596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73c16aa4625'
down_revision = 'abd815a13c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('total_correct_questions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_listening_duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('total_listening_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_correct_questions',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
