"""fix json field default values

Revision ID: a766855b99bd
Revises: 20611f1e3851
Create Date: 2026-03-27 09:51:58.116889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a766855b99bd'
down_revision = '20611f1e3851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.drop_column('two_thirds_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_thirds_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
