"""add fields to record user listening progress

Revision ID: c85c65673c69
Revises: 79f0e4dd884d
Create Date: 2026-03-18 19:41:13.139756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85c65673c69'
down_revision = '79f0e4dd884d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_position', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('two_thirds_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.drop_column('answers')
        batch_op.drop_column('two_thirds_count')
        batch_op.drop_column('last_position')

    # ### end Alembic commands ###
