"""add_invite_code

Revision ID: cbbdcec7114c
Revises: f4e8a1b9c0d2
Create Date: 2026-04-07 17:44:58.144149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbdcec7114c'
down_revision = 'f4e8a1b9c0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_teams_invite_code'), ['invite_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_invite_code'))
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
