"""add attribution fields to listening_exercise

Revision ID: d9267fcc1a1b
Revises: 440daf34526f
Create Date: 2026-04-01 17:42:54.860871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9267fcc1a1b'
down_revision = '440daf34526f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('source_author', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('license_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('total_correct_questions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_listening_duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('total_listening_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_correct_questions',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))

    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.drop_column('license_type')
        batch_op.drop_column('source_author')
        batch_op.drop_column('source_url')

    # ### end Alembic commands ###
