"""fix json field serialization issue

Revision ID: e66c2900c919
Revises: a766855b99bd
Create Date: 2026-03-27 10:22:15.720349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e66c2900c919'
down_revision = 'a766855b99bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.alter_column('permanent_answered',
               existing_type=sqlite.JSON(),
               type_=sa.PickleType(),
               existing_nullable=True)
        batch_op.alter_column('permanent_correct',
               existing_type=sqlite.JSON(),
               type_=sa.PickleType(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.alter_column('permanent_correct',
               existing_type=sa.PickleType(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('permanent_answered',
               existing_type=sa.PickleType(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
