"""empty message

Revision ID: e8fa8a97fa62
Revises: 65b01b6f68cd
Create Date: 2026-03-27 09:18:40.200683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fa8a97fa62'
down_revision = '65b01b6f68cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('audio_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_column('audio_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
