"""add subtitle_url

Revision ID: f6b07f736cb6
Revises: 
Create Date: 2026-03-13 01:07:44.002165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b07f736cb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaking_exercises')
    op.drop_table('user_speaking_progress')
    op.drop_table('user_speaking_submissions')
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listening_exercises', schema=None) as batch_op:
        batch_op.drop_column('subtitle_url')

    op.create_table('user_speaking_submissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('audio_filename', sa.VARCHAR(length=256), nullable=False),
    sa.Column('duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('feedback', sa.TEXT(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['speaking_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_speaking_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('audio_url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('transcript', sa.TEXT(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('feedback', sa.TEXT(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['speaking_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speaking_exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('prompt', sa.TEXT(), nullable=False),
    sa.Column('sample_answer', sa.TEXT(), nullable=True),
    sa.Column('difficulty', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('time_limit_seconds', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
