"""Add exercise completion times and question correct times fields

Revision ID: fb9fb72fb1e1
Revises: f4e8a1b9c0d2
Create Date: 2026-04-07 15:33:41.621919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9fb72fb1e1'
down_revision = 'f4e8a1b9c0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = set(inspector.get_table_names())

    if 'teams' not in tables:
        op.create_table('teams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('leader_id', sa.Integer(), nullable=False),
        sa.Column('avatar_url', sa.String(length=256), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )

    if 'team_members' not in tables:
        op.create_table('team_members',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.Column('joined_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'team_id')
        )
    with op.batch_alter_table('user_lands', schema=None) as batch_op:
        batch_op.alter_column('crop_water_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('crop_fertilizer_quality',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0.0'"))

    listening_columns = {
        column['name'] for column in inspector.get_columns('user_listening_progress')
    }
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        if 'exercise_completion_times' not in listening_columns:
            batch_op.add_column(sa.Column('exercise_completion_times', sa.JSON(), nullable=True))
        if 'question_correct_times' not in listening_columns:
            batch_op.add_column(sa.Column('question_correct_times', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_listening_progress', schema=None) as batch_op:
        batch_op.drop_column('question_correct_times')
        batch_op.drop_column('exercise_completion_times')

    with op.batch_alter_table('user_lands', schema=None) as batch_op:
        batch_op.alter_column('crop_fertilizer_quality',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0.0'"))
        batch_op.alter_column('crop_water_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    op.drop_table('team_members')
    op.drop_table('teams')
    # ### end Alembic commands ###
